import 'dart:convert';

import 'package:http/http.dart'as http;
import 'package:wigzawy/resorses/order_resors.dart';

class API{
 static const  String Api="http://bestbeast.naturalwigsbuy.com/api/";
static const  String orders_page=Api+"order_api";

// static const  String login=Api+"order_api";
// static const  String signup=Api+"order_api";
//////////////////////
///
//     static Future<List<dynamic>> fech()async{     
// final res = await http.get(
//   Uri.parse(orders_page));
//     if (res.statusCode == 200) {
//     print(res.body);
//     print("doooo");
//     // If the server did return a 200 OK response,
//     // then parse the JSON.
//           final parsed = json.decode(res.body).cast<Map<String, dynamic>>();

//     return parsed.map<Autogenerated>((item) => Autogenerated.fromJson(item)).toList();
//   } else {
//     // If the server did not return a 200 OK response,
//     // then throw an exception.
//     throw Exception('Failed to load album');
//   }
// }
///////////////////////
// http://bestbeast.naturalwigsbuy.com/api/order_api



Future fech() async {
  final url =orders_page;
  var response = await http.get(Uri.parse(url));
  Autogenerated model = Autogenerated.fromJson(json.decode(response.body)[0]);
  // now you can access your data.
  print(model);
}

}