
// import 'dart:async';
// import 'dart:convert';
// import 'package:http/http.dart' as http;
// import 'package:wigzawy/resorses/order_resors.dart';

// Future<Autogenerated> fetchAlbum() async {
//   // final response = await http
//   //     .get(Uri.parse('http://bestbeast.naturalwigsbuy.com/api/order_api'));
// final response = await http.get(
//   Uri.parse('http://bestbeast.naturalwigsbuy.com/api/order_api'),
//   // headers: {
//   //   'Content-Type': 'application/json',
//   //   'Accept': '*/*',
//   //   'Authorization': '101010',
//   // },
// );

//   if (response.statusCode == 200) {
//     print(response.body);
//     print("doooo");
//     // If the server did return a 200 OK response,
//     // then parse the JSON.
//     return Autogenerated.fromJson(jsonDecode(response.body));
//   } else {
//     // If the server did not return a 200 OK response,
//     // then throw an exception.
//     throw Exception('Failed to load album');
//   }
// }
