

import 'dart:convert';



class Autogenerated {
  int? id;
  String? refnum;
  String? image;
  int? cusId;
  String? density;
  String? name;
  String? createdAt;
  String? updatedAt;
  String? category;
  String? length;
  String? color;
  String? capsize;
  String? texture;
  int? quantity;
  String? captype;

  Autogenerated(
      {this.id,
      this.refnum,
      this.image,
      this.cusId,
      this.density,
      this.name,
      this.createdAt,
      this.updatedAt,
      this.category,
      this.length,
      this.color,
      this.capsize,
      this.texture,
      this.quantity,
      this.captype});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    refnum = json['refnum'];
    image = json['image'];
    cusId = json['cus_id'];
    density = json['density'];
    name = json['name'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    category = json['category'];
    length = json['length'];
    color = json['color'];
    capsize = json['capsize'];
    texture = json['texture'];
    quantity = json['quantity'];
    captype = json['captype'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['refnum'] = this.refnum;
    data['image'] = this.image;
    data['cus_id'] = this.cusId;
    data['density'] = this.density;
    data['name'] = this.name;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['category'] = this.category;
    data['length'] = this.length;
    data['color'] = this.color;
    data['capsize'] = this.capsize;
    data['texture'] = this.texture;
    data['quantity'] = this.quantity;
    data['captype'] = this.captype;
    return data;
  }
}